name: gitbaker
description: An easy and simple to integrate info baker for git repositories into your Flutter or Dart project.
version: 0.0.1
repository: https://github.com/JHubi1/gitbaker

topics:
  - git
  - gitbaker

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.5.0
  yaml: ^3.1.3
  intl: ^0.20.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
