name: gitbaker
description: An easy and simple to integrate info baker for git repositories into your Flutter or Dart project.
version: 0.0.4
repository: https://github.com/JHubi1/gitbaker

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - git
  - gitbaker

environment:
  sdk: ^3.6.0

dependencies:
  yaml: ^3.1.3
  intl: ^0.20.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
